# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.4.2
FROM docker.io/library/ruby:${RUBY_VERSION}-slim

WORKDIR /rails

ENV RAILS_ENV="test" \
    BUNDLE_WITHOUT="development" \
    CUPRITE_BROWSER_PATH="/usr/bin/chromium" \
    CUPRITE_NO_SANDBOX="1"

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential chromium chromium-sandbox git libvips sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN groupadd --system --gid 1000 rails && \
    useradd --system --uid 1000 --gid rails --create-home rails

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY --chown=rails:rails . .
USER rails

CMD ["bin/rails", "test:system"]
